---
title: "modelfitplots"
output: html_document
date: "2025-03-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary

Takes model and data in csv called `fitforplotnoK.csv` which was made in `optimise_noK.Rmd`. 



```{r, include=FALSE}
library(RColorBrewer)
library(tidyverse)
```

```{r}
df <- read.csv('fitforplotnoK.csv') # 216 obs of 18 - only the actual values of A/B
#df[is.na(df)] <- 0

```




```{r, include=FALSE}


df$trial_type <- recode(df$trial_id, 
                      "1_c1"="A=0,B=0,E=0",
                      "1_c2"="A=0,B=1,E=0",
                      "1_c3"="A=1,B=0,E=0",
                      "1_c4"="A=1,B=1,E=0",
                      "1_c5"="A=1,B=1,E=1",
                      "1_d1"="A=0,B=0,E=0",
                      "1_d2"="A=0,B=1,E=0",
                      "1_d3"="A=0,B=1,E=1",
                      "1_d4"="A=1,B=0,E=0",
                      "1_d5"="A=1,B=0,E=1",
                      "1_d6"="A=1,B=1,E=0",
                      "1_d7"="A=1,B=1,E=1",
                      "2_c1"="A=0,B=0,E=0",
                      "2_c2"="A=0,B=1,E=0",
                      "2_c3"="A=1,B=0,E=0",
                      "2_c4"="A=1,B=1,E=0",
                      "2_c5"="A=1,B=1,E=1",
                      "2_d1"="A=0,B=0,E=0",
                      "2_d2"="A=0,B=1,E=0",
                      "2_d3"="A=0,B=1,E=1",
                      "2_d4"="A=1,B=0,E=0",
                      "2_d5"="A=1,B=0,E=1",
                      "2_d6"="A=1,B=1,E=0",
                      "2_d7"="A=1,B=1,E=1",
                      "3_c1"="A=0,B=0,E=0",
                      "3_c2"="A=0,B=1,E=0",
                      "3_c3"="A=1,B=0,E=0",
                      "3_c4"="A=1,B=1,E=0",
                      "3_c5"="A=1,B=1,E=1",
                      "3_d1"="A=0,B=0,E=0",
                      "3_d2"="A=0,B=1,E=0",
                      "3_d3"="A=0,B=1,E=1",
                      "3_d4"="A=1,B=0,E=0",
                      "3_d5"="A=1,B=0,E=1",
                      "3_d6"="A=1,B=1,E=0",
                      "3_d7"="A=1,B=1,E=1")

df$trial_structure_type <- recode(df$trial_id, 
                                "1_c1"="Conjunctive: A=0,B=0,E=0",
                                "1_c2"="Conjunctive: A=0,B=1,E=0",
                                "1_c3"="Conjunctive: A=1,B=0,E=0",
                                "1_c4"="Conjunctive: A=1,B=1,E=0",
                                "1_c5"="Conjunctive: A=1,B=1,E=1",
                                "1_d1"="Disjunctive: A=0,B=0,E=0",
                                "1_d2"="Disjunctive: A=0,B=1,E=0",
                                "1_d3"="Disjunctive: A=0,B=1,E=1",
                                "1_d4"="Disjunctive: A=1,B=0,E=0",
                                "1_d5"="Disjunctive: A=1,B=0,E=1",
                                "1_d6"="Disjunctive: A=1,B=1,E=0",
                                "1_d7"="Disjunctive: A=1,B=1,E=1",
                                "2_c1"="Conjunctive: A=0,B=0,E=0",
                                "2_c2"="Conjunctive: A=0,B=1,E=0",
                                "2_c3"="Conjunctive: A=1,B=0,E=0",
                                "2_c4"="Conjunctive: A=1,B=1,E=0",
                                "2_c5"="Conjunctive: A=1,B=1,E=1",
                                "2_d1"="Disjunctive: A=0,B=0,E=0",
                                "2_d2"="Disjunctive: A=0,B=1,E=0",
                                "2_d3"="Disjunctive: A=0,B=1,E=1",
                                "2_d4"="Disjunctive: A=1,B=0,E=0",
                                "2_d5"="Disjunctive: A=1,B=0,E=1",
                                "2_d6"="Disjunctive: A=1,B=1,E=0",
                                "2_d7"="Disjunctive: A=1,B=1,E=1",
                                "3_c1"="Conjunctive: A=0,B=0,E=0",
                                "3_c2"="Conjunctive: A=0,B=1,E=0",
                                "3_c3"="Conjunctive: A=1,B=0,E=0",
                                "3_c4"="Conjunctive: A=1,B=1,E=0",
                                "3_c5"="Conjunctive: A=1,B=1,E=1",
                                "3_d1"="Disjunctive: A=0,B=0,E=0",
                                "3_d2"="Disjunctive: A=0,B=1,E=0",
                                "3_d3"="Disjunctive: A=0,B=1,E=1",
                                "3_d4"="Disjunctive: A=1,B=0,E=0",
                                "3_d5"="Disjunctive: A=1,B=0,E=1",
                                "3_d6"="Disjunctive: A=1,B=1,E=0",
                                "3_d7"="Disjunctive: A=1,B=1,E=1")

df<- df %>% mutate(trial_type = factor(trial_type, levels = c("A=0,B=0,E=0",
                                                              "A=0,B=1,E=0",
                                                              "A=0,B=1,E=1",
                                                              "A=1,B=0,E=0",
                                                              "A=1,B=0,E=1",
                                                              "A=1,B=1,E=0",
                                                              "A=1,B=1,E=1")),
                   trial_structure_type = factor(trial_structure_type, levels = c("Conjunctive: A=1,B=1,E=1",
                                                                                  "Conjunctive: A=1,B=1,E=0",
                                                                                  "Conjunctive: A=1,B=0,E=0",
                                                                                  "Conjunctive: A=0,B=1,E=0",
                                                                                  "Conjunctive: A=0,B=0,E=0",
                                                                                  "Disjunctive: A=0,B=1,E=0",
                                                                                  "Disjunctive: A=1,B=1,E=1",
                                                                                  "Disjunctive: A=1,B=0,E=1",
                                                                                  "Disjunctive: A=0,B=1,E=1",
                                                                                  "Disjunctive: A=1,B=1,E=0",
                                                                                  "Disjunctive: A=1,B=0,E=0",
                                                                                  "Disjunctive: A=0,B=0,E=0")),
                   # NOTE THESE (ABOVE) LOOK IN THE WRONG ORDER BUT ITS JUST FOR THE PLOT
                   pgroup = factor(pgroup, levels = 1:3, labels = c('A=.1,Au=.5,B=.8,Bu=.5',
                                                                            'A=.5,Au=.1,B=.5,Bu=.8',
                                                                            'A=.1,Au=.7,B=.8,Bu=.5')),
                   Response = factor(node3),
                   Observed = factor(!Response%in%c('Au=0','Au=1','Bu=0', 'Bu=1'), levels = c(T,F)),
                   Variable = factor(substr(node3, 1, 1)),
                   #State = factor(rep(c(0,1), 144)),
                   Actual = factor(Actual, levels = c(FALSE, TRUE), labels = c('FALSE', 'TRUE')))


```



### So now to plot! Fig.3

Need to add SE 

```{r}
df$SE <- NA


for (i in unique(df$trial_id))
{
  df$SE[df$trial_id==i]<-sqrt((df$prop[df$trial_id==i] * (1-df$prop[df$trial_id==i])) / sum(df$n[df$trial_id==i]))
}

```



```{r, include=FALSE}
ggplot(df %>% filter(pgroup=='A=.1,Au=.7,B=.8,Bu=.5'), aes(x=node3, y=prop, fill=Observed, colour = Actual)) +
  geom_bar(stat = 'identity') +
  geom_errorbar(aes(ymin=prop-SE, ymax=prop+SE), width=.2) + 
  labs(x = 'Response', y = 'Proportion/Prediction')+
  scale_fill_brewer(palette = "Set2")+
  scale_colour_manual(values = c('gray', 'black')) +
  geom_point(aes(y=full), colour = 'black') +
  geom_rect(data = subset(df, trial_structure_type %in% c("Conjunctive: A=1,B=1,E=1", "Disjunctive: A=1,B=1,E=1")), 
            fill = NA, colour = "blue", xmin = -Inf,xmax = Inf, linewidth = 2,
            ymin = -Inf,ymax = Inf) +
  facet_wrap( ~ trial_structure_type, ncol = 6) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.margin=margin(c(0,0,0,0)),
        axis.title.x = element_text(margin = margin(t = 1, r =0, b = 0, l = 0))) 
```

```{r}
ggsave('resultsnoK.pdf', width = 12, height = 4)
```

# Do same for other pgroups


```{r, include=FALSE}
ggplot(df %>% filter(pgroup=='A=.1,Au=.5,B=.8,Bu=.5'), aes(x=node3, y=prop, fill=Observed, colour = Actual)) +
  geom_bar(stat = 'identity') +
  geom_errorbar(aes(ymin=prop-SE, ymax=prop+SE), width=.2) + 
  labs(x = 'Response', y = 'Proportion/Prediction')+
  scale_fill_brewer(palette = "Set2")+
  scale_colour_manual(values = c('gray', 'black')) +
  geom_point(aes(y=full), colour = 'black') +
  geom_rect(data = subset(df, trial_structure_type %in% c("Conjunctive: A=1,B=1,E=1", "Disjunctive: A=1,B=1,E=1")), 
            fill = NA, colour = "blue", xmin = -Inf,xmax = Inf, linewidth = 2,
            ymin = -Inf,ymax = Inf) +
  facet_wrap( ~ trial_structure_type, ncol = 6) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.margin=margin(c(0,0,0,0)),
        axis.title.x = element_text(margin = margin(t = 1, r =0, b = 0, l = 0))) 

```

```{r}
ggsave('results_setting1.pdf', width = 12, height = 4)
```




```{r, include=FALSE}
ggplot(df %>% filter(pgroup=='A=.5,Au=.1,B=.5,Bu=.8'), aes(x=node3, y=prop, fill=Observed, colour = Actual)) +
  geom_bar(stat = 'identity') +
  geom_errorbar(aes(ymin=prop-SE, ymax=prop+SE), width=.2) + 
  labs(x = 'Response', y = 'Proportion/Prediction')+
  scale_fill_brewer(palette = "Set2")+
  scale_colour_manual(values = c('gray', 'black')) +
  geom_point(aes(y=full), colour = 'black') +
  geom_rect(data = subset(df, trial_structure_type %in% c("Conjunctive: A=1,B=1,E=1", "Disjunctive: A=1,B=1,E=1")), 
            fill = NA, colour = "blue", xmin = -Inf,xmax = Inf, linewidth = 2,
            ymin = -Inf,ymax = Inf) +
  facet_wrap( ~ trial_structure_type, ncol = 6) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.margin=margin(c(0,0,0,0)),
        axis.title.x = element_text(margin = margin(t = 1, r =0, b = 0, l = 0))) 

```

```{r}
ggsave('results_setting2.pdf', width = 12, height = 4)
```


(We also plan a shiny app to compare other model predictions, check back later to see if we've done it yet)

# Fig 4 - just the 111 for abnormal inflation

For now just 'simple 111' and 'obs un'

```{r}
row_labeller <- c(
  "A=.1,Au=.5,B=.8,Bu=.5"=".1,.5,.8,.5",
  "A=.5,Au=.1,B=.5,Bu=.8"=".5,.1,.5,.8",
  "A=.1,Au=.7,B=.8,Bu=.5"=".1,.7,.8,.5"
)

column_labeller <- c(
  "Conjunctive: A=1,B=1,E=1"="Conjunctive",
  "Disjunctive: A=1,B=1,E=1"="Disjunctive"
)
```

```{r}
ggplot(df %>% filter(trial_structure_type %in% c("Conjunctive: A=1,B=1,E=1", "Disjunctive: A=1,B=1,E=1"), Actual == T),
       aes(x=Variable, y=prop, fill=Observed)) +
  geom_bar(stat = 'identity', colour = 'black', position = position_dodge()) +
  geom_errorbar(aes(ymin=prop-SE, ymax=prop+SE), width=.2, position = position_dodge(.9)) + 
  labs(x = 'Response', y = 'Proportion/Prediction')+
  scale_fill_brewer(palette = "Set2")+
  geom_point(data = df %>% filter(trial_structure_type %in% c("Conjunctive: A=1,B=1,E=1", "Disjunctive: A=1,B=1,E=1"), Actual==T), aes(y=full), colour = 'black', position = position_dodge(.9)) +
  # geom_point(aes(y=noInf), colour = 'black', shape = 2) +
  # geom_point(aes(y=noSelect), colour = 'black', shape = 3) +
  facet_grid(trial_structure_type ~ pgroup,
             labeller = labeller(pgroup = row_labeller, trial_structure_type = column_labeller)) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        legend.position = 'none',
        axis.title.x = element_text(margin = margin(t = 1, r =0, b = 0, l = 0))) 
```

```{r}
ggsave('results_simple_111.pdf', width = 3, height = 3)   
```


```{r}
df.l<-df %>% 
  gather(key, val, c(prop, full)) %>% 
  mutate(key = factor(key, 
                      levels = c('prop', 'full'),
                      labels = c("Participants", "Full Model"))) %>%
  group_by(Observed, key, trial_structure_type) %>% 
  summarise(val = sum(val)/3)
```

```{r}
ggplot(df.l, aes(y=val, x=key, fill=Observed)) +
  stat_summary(fun = mean,
               geom = "bar",
               position = position_dodge(), colour = 'black') +
stat_summary(fun.data = mean_se, geom = "errorbar",  position = position_dodge(.9), width = .2)+
  labs(x = 'Response', y = 'Proportion/Prediction') +
  scale_fill_brewer(palette = "Set2") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.margin=margin(c(0,0,0,0)),
        legend.position = c(-.1,-.2),
        axis.title.x = element_text(margin = margin(t = 1, r =0, b = 0, l = 0))) 
```


```{r}
ggsave('results_obs_un.pdf', width = 2, height = 3)  
```






